### ISSUE TITLE
verify: "Unexpected char: P" "Unexpected char: A"

### ISSUE THREAD

**Issue by powerman** [issuu/sure-deploy#32]
I've weird issue with `verify` command while `converge` works just fine:

```
$ cat mon.env.sh
export MON_AM_ADDR_HOST=am.admin.redacted
export MON_AM_SLACK_ENDPOINT=https://hooks.slack.com/services/redacted/redacted/redacted
export MON_GRAFANA_ADDR_HOST=grafana.admin.redacted
export MON_PROM_ADDR_HOST=prom.admin.redacted
$ docker run -i -t --rm \
    --group-add=$(stat -c %g /var/run/docker.sock) -v /var/run/docker.sock:/var/run/docker.sock \
    -v $PWD/mon.yml:/home/opam/docker-compose.yml:ro \
    -e PROM_IMAGE_TAG=redacted/mon:prom-b48ea17165b420c4ecb8f3c7001cb63a86b7eefc \
    -e AM_IMAGE_TAG=redacted/mon:am-540912563616c42e09043e321fef944e57f365eb \
    --env-file=<(sed 's/^export //' mon.env.sh) \
    issuu/sure-deploy:183 \
    converge --socket /var/run/docker.sock --timeout 15 --verbose mon
2020-08-29 07:08:42.870147Z Info Services detected in 'mon' stack: mon_grafana, mon_prometheus, mon_alertmanager
2020-08-29 07:08:42.872508Z Info Stack 'mon' has converged
$ docker run -i -t --rm \
    --group-add=$(stat -c %g /var/run/docker.sock) -v /var/run/docker.sock:/var/run/docker.sock \
    -v $PWD/mon.yml:/home/opam/docker-compose.yml:ro \
    -e PROM_IMAGE_TAG=redacted/mon:prom-b48ea17165b420c4ecb8f3c7001cb63a86b7eefc \
    -e AM_IMAGE_TAG=redacted/mon:am-540912563616c42e09043e321fef944e57f365eb \
    --env-file=<(sed 's/^export //' mon.env.sh) \
    issuu/sure-deploy:183 \
    verify --socket /var/run/docker.sock --verbose mon
("Unexpected char: P" "Unexpected char: A")
$
```

<details><summary>mon.yml</summary>

```yml
version: '3.7'

networks:
    cpdpro:
        external: true

volumes:
    prometheus:
    grafana:
    alertmanager:

services:

    prometheus:
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - 'node.labels.prometheus == true'
            update_config:
                delay: 15s
                monitor: 15s
                failure_action: rollback
        image: '${PROM_IMAGE_TAG:?}'
        networks:
            cpdpro:
        volumes:
            - prometheus:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--web.external-url=https://${MON_PROM_ADDR_HOST:?}'
            - '--web.route-prefix=/'

    grafana:
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - 'node.labels.grafana == true'
            update_config:
                delay: 15s
                monitor: 15s
                failure_action: rollback
        image: 'grafana/grafana:7.1.4'
        networks:
            cpdpro:
        volumes:
            - grafana:/var/lib/grafana
        environment:
            GF_SERVER_DOMAIN:           '${MON_GRAFANA_ADDR_HOST:?}'
            GF_USERS_ALLOW_SIGN_UP:     'false'
            GF_USERS_ALLOW_ORG_CREATE:  'false'
            GF_LOG_MODE:                'console'

    alertmanager:
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - 'node.labels.alertmanager == true'
            update_config:
                delay: 15s
                monitor: 15s
                failure_action: rollback
        image: '${AM_IMAGE_TAG:?}'
        networks:
            cpdpro:
        volumes:
            - alertmanager:/alertmanager
        environment:
            MON_AM_SLACK_ENDPOINT:      '${MON_AM_SLACK_ENDPOINT:?}'
        command:
            - '--config.file=/etc/alertmanager/alertmanager.yml'
            - '--storage.path=/alertmanager'
            - '--web.external-url=https://${MON_AM_ADDR_HOST:?}'
            - '--web.route-prefix=/'
```
</details>

<details><summary>docker info</summary>

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 14
  Running: 7
  Paused: 0
  Stopped: 7
 Images: 14
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: awslogs
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: nszovl7yo0czrw6ajvmwcwvou
  Is Manager: true
  ClusterID: ee7zexvhkqh1r5vc2sovq8i2b
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: redacted
  Manager Addresses:
   redacted:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1065-aws
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.618GiB
 Name: redacted
 ID: 5MZS:GT6I:5FGU:QDJS:IAQF:7KGO:LY4B:BNFO:256T:2BCX:JKWV:MJ2S
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: redacted
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
</details>

I'm using private repo on Docker Hub, so it needs auth and I use `docker stack deploy --with-registry-auth`, so maybe this issue happens because I didn't provide `--registry-access` option to `verify` - but I can't figure out which value should be provided to this flag for default docker registry (Hub). Here is my `~/.docker/config.json`:

```json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "redacted"
		}
	}
}
```
